development:
  adapter: postgresql
  database: kourti
  host:  localhost
  pool: 5
  timeout: 5000
  username: geeksters
  password: geeksters

test:
  adapter: postgresql
  database: kourti_test<%= ENV['TEST_ENV_NUMBER'] %>
  host:  localhost
  pool: 5
  timeout: 5000
  username: geeksters
  password: geeksters

production:
  adapter: postgresql
  database: kourti
  host:  localhost
  pool: 5
  timeout: 5000
  username: geeksters
  password: geeksters